name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Trigger on push to the main branch
    workflow_dispatch:

env:
    VITE_BASE_API_URL: ${{ secrets.VITE_BASE_API_URL }}

jobs:
    build:
        runs-on: ubuntu-latest
        environment: github-pages # Specify the GitHub environment

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2

            # Set up Node.js (with the correct version from your `package.json`)
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21' # Change this if you need a different version

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Debugging the environment variable
            - name: Verify Environment Variable
              run: echo "VITE_BASE_API_URL=${{ secrets.VITE_BASE_API_URL }}"

            # Run the build process using Vite
            - name: Build the project
              run: npm run build
              env:
                  VITE_BASE_API_URL: ${{ secrets.VITE_BASE_API_URL }}

            # Deploy to GitHub Pages using peaceiris/actions-gh-pages
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
